"""Baseline: the whole schema as it existed before Alembic took over.

Revision ID: 0001_baseline
Revises:
Create Date: 2026-09-29

Autogenerated from the models against an empty database. Until this revision the schema was
built by Base.metadata.create_all plus hand-written ALTERs at app startup (main.py).

A database created that way already has these tables, so it must NOT run this upgrade. It has
also drifted from the models (create_all never altered existing tables). Adopt it once with

    python scripts/adopt_legacy_db.py --apply

which stamps it at this revision, upgrades, and fixes the drift in a single transaction.
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '0001_baseline'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table('app_settings',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('dim_categories',
    sa.Column('category_id', sa.BigInteger(), nullable=False),
    sa.Column('category_name', sa.String(length=255), nullable=False),
    sa.Column('parent_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['dim_categories.category_id'], ),
    sa.PrimaryKeyConstraint('category_id')
    )
    op.create_index(op.f('ix_dim_categories_category_name'), 'dim_categories', ['category_name'], unique=False)
    op.create_index(op.f('ix_dim_categories_parent_id'), 'dim_categories', ['parent_id'], unique=False)
    op.create_table('dim_date',
    sa.Column('date_id', sa.Date(), nullable=False),
    sa.Column('day', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('week', sa.Integer(), nullable=False),
    sa.Column('quarter', sa.Integer(), nullable=False),
    sa.Column('is_weekend', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('date_id')
    )
    op.create_index(op.f('ix_dim_date_is_weekend'), 'dim_date', ['is_weekend'], unique=False)
    op.create_index(op.f('ix_dim_date_month'), 'dim_date', ['month'], unique=False)
    op.create_index(op.f('ix_dim_date_quarter'), 'dim_date', ['quarter'], unique=False)
    op.create_index(op.f('ix_dim_date_week'), 'dim_date', ['week'], unique=False)
    op.create_index(op.f('ix_dim_date_year'), 'dim_date', ['year'], unique=False)
    op.create_table('raw_ga4_cart_products',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('item_name', sa.String(length=500), nullable=False),
    sa.Column('item_id', sa.String(length=100), nullable=True),
    sa.Column('add_to_cart_count', sa.Integer(), nullable=False),
    sa.Column('purchase_count', sa.Integer(), nullable=False),
    sa.Column('item_revenue', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('loaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', 'item_name', name='uq_ga4_cart_prod_date_item')
    )
    op.create_index(op.f('ix_raw_ga4_cart_products_date'), 'raw_ga4_cart_products', ['date'], unique=False)
    op.create_table('raw_ga4_devices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('device_category', sa.String(length=50), nullable=False),
    sa.Column('browser', sa.String(length=100), nullable=False),
    sa.Column('os', sa.String(length=100), nullable=False),
    sa.Column('sessions', sa.Integer(), nullable=False),
    sa.Column('users', sa.Integer(), nullable=False),
    sa.Column('loaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', 'device_category', 'browser', 'os', name='uq_ga4_devices_date_dev')
    )
    op.create_index(op.f('ix_raw_ga4_devices_date'), 'raw_ga4_devices', ['date'], unique=False)
    op.create_table('raw_ga4_funnel',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('view_item', sa.Integer(), nullable=False),
    sa.Column('add_to_cart', sa.Integer(), nullable=False),
    sa.Column('begin_checkout', sa.Integer(), nullable=False),
    sa.Column('add_payment_info', sa.Integer(), nullable=False),
    sa.Column('purchase', sa.Integer(), nullable=False),
    sa.Column('remove_from_cart', sa.Integer(), nullable=False),
    sa.Column('add_to_cart_value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('purchase_value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('loaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', name='uq_ga4_funnel_date')
    )
    op.create_index(op.f('ix_raw_ga4_funnel_date'), 'raw_ga4_funnel', ['date'], unique=False)
    op.create_table('raw_ga4_funnel_devices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('device_category', sa.String(length=50), nullable=False),
    sa.Column('view_item', sa.Integer(), nullable=False),
    sa.Column('add_to_cart', sa.Integer(), nullable=False),
    sa.Column('begin_checkout', sa.Integer(), nullable=False),
    sa.Column('add_payment_info', sa.Integer(), nullable=False),
    sa.Column('purchase', sa.Integer(), nullable=False),
    sa.Column('remove_from_cart', sa.Integer(), nullable=False),
    sa.Column('loaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', 'device_category', name='uq_ga4_funnel_dev_date_device')
    )
    op.create_index(op.f('ix_raw_ga4_funnel_devices_date'), 'raw_ga4_funnel_devices', ['date'], unique=False)
    op.create_table('raw_ga4_geo',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('city', sa.String(length=200), nullable=False),
    sa.Column('sessions', sa.Integer(), nullable=False),
    sa.Column('users', sa.Integer(), nullable=False),
    sa.Column('new_users', sa.Integer(), nullable=False),
    sa.Column('loaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', 'country', 'city', name='uq_ga4_geo_date_loc')
    )
    op.create_index(op.f('ix_raw_ga4_geo_date'), 'raw_ga4_geo', ['date'], unique=False)
    op.create_table('raw_ga4_pages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('page_path', sa.String(length=1000), nullable=False),
    sa.Column('page_title', sa.String(length=500), nullable=True),
    sa.Column('page_views', sa.Integer(), nullable=False),
    sa.Column('avg_time_on_page', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('entrances', sa.Integer(), nullable=False),
    sa.Column('exits', sa.Integer(), nullable=False),
    sa.Column('bounce_rate', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('loaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', 'page_path', name='uq_ga4_pages_date_path')
    )
    op.create_index(op.f('ix_raw_ga4_pages_date'), 'raw_ga4_pages', ['date'], unique=False)
    op.create_table('raw_ga4_sources',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('medium', sa.String(length=255), nullable=False),
    sa.Column('campaign', sa.String(length=500), nullable=True),
    sa.Column('sessions', sa.Integer(), nullable=False),
    sa.Column('users', sa.Integer(), nullable=False),
    sa.Column('new_users', sa.Integer(), nullable=False),
    sa.Column('engaged_sessions', sa.Integer(), nullable=False),
    sa.Column('conversions', sa.Integer(), nullable=False),
    sa.Column('revenue', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('loaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', 'source', 'medium', name='uq_ga4_sources_date_src_med')
    )
    op.create_index(op.f('ix_raw_ga4_sources_date'), 'raw_ga4_sources', ['date'], unique=False)
    op.create_table('raw_ga4_traffic',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('sessions', sa.Integer(), nullable=False),
    sa.Column('total_users', sa.Integer(), nullable=False),
    sa.Column('new_users', sa.Integer(), nullable=False),
    sa.Column('page_views', sa.Integer(), nullable=False),
    sa.Column('bounce_rate', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('avg_session_duration', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('engaged_sessions', sa.Integer(), nullable=False),
    sa.Column('events_count', sa.Integer(), nullable=False),
    sa.Column('loaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', name='uq_ga4_traffic_date')
    )
    op.create_index(op.f('ix_raw_ga4_traffic_date'), 'raw_ga4_traffic', ['date'], unique=False)
    op.create_table('stores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('api_url', sa.String(length=255), nullable=False),
    sa.Column('api_token', sa.String(length=255), nullable=False),
    sa.Column('api_login', sa.String(length=255), nullable=True),
    sa.Column('api_password', sa.String(length=255), nullable=True),
    sa.Column('api_token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('api_token_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_sync_orders', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_sync_products', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_sync_customers', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('shoper_customer_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('orders_count', sa.Integer(), nullable=False),
    sa.Column('total_spent', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('first_order_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_order_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_email'), 'customers', ['email'], unique=False)
    op.create_index(op.f('ix_customers_shoper_customer_id'), 'customers', ['shoper_customer_id'], unique=False)
    op.create_index(op.f('ix_customers_store_id'), 'customers', ['store_id'], unique=False)
    op.create_table('dim_customers',
    sa.Column('customer_id', sa.BigInteger(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('first_order_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_order_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_orders', sa.Integer(), nullable=False),
    sa.Column('total_revenue', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('customer_type', sa.String(length=50), nullable=True),
    sa.Column('rfm_score', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('customer_id')
    )
    op.create_index(op.f('ix_dim_customers_customer_type'), 'dim_customers', ['customer_type'], unique=False)
    op.create_index(op.f('ix_dim_customers_first_order_date'), 'dim_customers', ['first_order_date'], unique=False)
    op.create_index(op.f('ix_dim_customers_last_order_date'), 'dim_customers', ['last_order_date'], unique=False)
    op.create_index(op.f('ix_dim_customers_rfm_score'), 'dim_customers', ['rfm_score'], unique=False)
    op.create_index(op.f('ix_dim_customers_store_id'), 'dim_customers', ['store_id'], unique=False)
    op.create_index(op.f('ix_dim_customers_total_revenue'), 'dim_customers', ['total_revenue'], unique=False)
    op.create_table('dim_products',
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(length=500), nullable=False),
    sa.Column('category_id', sa.BigInteger(), nullable=True),
    sa.Column('brand', sa.String(length=255), nullable=True),
    sa.Column('cost_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('retail_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('product_id')
    )
    op.create_index(op.f('ix_dim_products_brand'), 'dim_products', ['brand'], unique=False)
    op.create_index(op.f('ix_dim_products_category_id'), 'dim_products', ['category_id'], unique=False)
    op.create_index(op.f('ix_dim_products_is_active'), 'dim_products', ['is_active'], unique=False)
    op.create_index(op.f('ix_dim_products_product_name'), 'dim_products', ['product_name'], unique=False)
    op.create_index(op.f('ix_dim_products_retail_price'), 'dim_products', ['retail_price'], unique=False)
    op.create_index(op.f('ix_dim_products_store_id'), 'dim_products', ['store_id'], unique=False)
    op.create_table('fact_orders',
    sa.Column('order_id', sa.BigInteger(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.BigInteger(), nullable=True),
    sa.Column('order_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payment_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('order_status', sa.String(length=50), nullable=True),
    sa.Column('payment_status', sa.String(length=50), nullable=True),
    sa.Column('shipment_status', sa.String(length=50), nullable=True),
    sa.Column('gross_value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('net_value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('discount_value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('shipping_value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tax_value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('margin_value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('items_count', sa.Integer(), nullable=False),
    sa.Column('source_channel', sa.String(length=100), nullable=True),
    sa.Column('campaign', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('order_id')
    )
    op.create_index(op.f('ix_fact_orders_customer_id'), 'fact_orders', ['customer_id'], unique=False)
    op.create_index(op.f('ix_fact_orders_gross_value'), 'fact_orders', ['gross_value'], unique=False)
    op.create_index(op.f('ix_fact_orders_order_date'), 'fact_orders', ['order_date'], unique=False)
    op.create_index(op.f('ix_fact_orders_order_status'), 'fact_orders', ['order_status'], unique=False)
    op.create_index(op.f('ix_fact_orders_source_channel'), 'fact_orders', ['source_channel'], unique=False)
    op.create_index(op.f('ix_fact_orders_store_id'), 'fact_orders', ['store_id'], unique=False)
    op.create_table('price_update_jobs',
    sa.Column('job_id', sa.String(length=32), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=512), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('target_mode', sa.String(length=20), nullable=False),
    sa.Column('csv_delimiter', sa.String(length=20), nullable=False),
    sa.Column('disable_extra_variants', sa.Boolean(), nullable=False),
    sa.Column('duplicate_mode', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('processed', sa.Integer(), nullable=False),
    sa.Column('success', sa.Integer(), nullable=False),
    sa.Column('failed', sa.Integer(), nullable=False),
    sa.Column('skipped', sa.Integer(), nullable=False),
    sa.Column('warning', sa.Integer(), nullable=False),
    sa.Column('deactivated_variants', sa.Integer(), nullable=False),
    sa.Column('log_seq', sa.Integer(), nullable=False),
    sa.Column('logs_dropped', sa.Integer(), nullable=False),
    sa.Column('current_row_number', sa.Integer(), nullable=True),
    sa.Column('current_code', sa.String(length=200), nullable=True),
    sa.Column('current_phase', sa.String(length=40), nullable=True),
    sa.Column('fatal_error', sa.Text(), nullable=True),
    sa.Column('validation_errors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('job_id')
    )
    op.create_index(op.f('ix_price_update_jobs_status'), 'price_update_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_price_update_jobs_store_id'), 'price_update_jobs', ['store_id'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('shoper_product_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=True),
    sa.Column('ean', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('category_name', sa.String(length=255), nullable=True),
    sa.Column('producer_name', sa.String(length=255), nullable=True),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('stock_quantity', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('synced_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_code'), 'products', ['code'], unique=False)
    op.create_index(op.f('ix_products_shoper_product_id'), 'products', ['shoper_product_id'], unique=False)
    op.create_index(op.f('ix_products_store_id'), 'products', ['store_id'], unique=False)
    op.create_table('raw_categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.BigInteger(), nullable=False),
    sa.Column('root', sa.Boolean(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('translations', sa.JSON(), nullable=True),
    sa.Column('loaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id', 'category_id', name='uq_raw_categories_store_category')
    )
    op.create_index(op.f('ix_raw_categories_category_id'), 'raw_categories', ['category_id'], unique=False)
    op.create_index(op.f('ix_raw_categories_loaded_at'), 'raw_categories', ['loaded_at'], unique=False)
    op.create_index(op.f('ix_raw_categories_store_id'), 'raw_categories', ['store_id'], unique=False)
    op.create_table('raw_currencies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('currency_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=10), nullable=True),
    sa.Column('rate', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('rate_sync', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('rate_date', sa.String(length=50), nullable=True),
    sa.Column('loaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id', 'currency_id', name='uq_raw_currencies_store_currency')
    )
    op.create_index(op.f('ix_raw_currencies_currency_id'), 'raw_currencies', ['currency_id'], unique=False)
    op.create_index(op.f('ix_raw_currencies_loaded_at'), 'raw_currencies', ['loaded_at'], unique=False)
    op.create_index(op.f('ix_raw_currencies_store_id'), 'raw_currencies', ['store_id'], unique=False)
    op.create_table('raw_customers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('firstname', sa.String(length=100), nullable=True),
    sa.Column('lastname', sa.String(length=100), nullable=True),
    sa.Column('date_add', sa.String(length=50), nullable=True),
    sa.Column('lastvisit', sa.String(length=50), nullable=True),
    sa.Column('discount', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('origin', sa.Integer(), nullable=True),
    sa.Column('loaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id', 'user_id', name='uq_raw_customers_store_user')
    )
    op.create_index(op.f('ix_raw_customers_email'), 'raw_customers', ['email'], unique=False)
    op.create_index(op.f('ix_raw_customers_loaded_at'), 'raw_customers', ['loaded_at'], unique=False)
    op.create_index(op.f('ix_raw_customers_store_id'), 'raw_customers', ['store_id'], unique=False)
    op.create_index(op.f('ix_raw_customers_user_id'), 'raw_customers', ['user_id'], unique=False)
    op.create_table('raw_discounts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('discount_type', sa.String(length=50), nullable=False),
    sa.Column('promo_code_id', sa.BigInteger(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('code', sa.String(length=100), nullable=True),
    sa.Column('discount_type_code', sa.Integer(), nullable=True),
    sa.Column('discount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('max_discount_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('time_from', sa.String(length=50), nullable=True),
    sa.Column('time_to', sa.String(length=50), nullable=True),
    sa.Column('min_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('usage_limit', sa.Integer(), nullable=True),
    sa.Column('peruser_limit', sa.Integer(), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=True),
    sa.Column('active', sa.Integer(), nullable=True),
    sa.Column('promo_id', sa.BigInteger(), nullable=True),
    sa.Column('product_id', sa.BigInteger(), nullable=True),
    sa.Column('stock_id', sa.BigInteger(), nullable=True),
    sa.Column('date_from', sa.String(length=50), nullable=True),
    sa.Column('date_to', sa.String(length=50), nullable=True),
    sa.Column('discount_wholesale', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('discount_special', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('condition_type', sa.Integer(), nullable=True),
    sa.Column('stocks', sa.JSON(), nullable=True),
    sa.Column('loaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raw_discounts_code'), 'raw_discounts', ['code'], unique=False)
    op.create_index(op.f('ix_raw_discounts_discount_type'), 'raw_discounts', ['discount_type'], unique=False)
    op.create_index(op.f('ix_raw_discounts_loaded_at'), 'raw_discounts', ['loaded_at'], unique=False)
    op.create_index(op.f('ix_raw_discounts_product_id'), 'raw_discounts', ['product_id'], unique=False)
    op.create_index(op.f('ix_raw_discounts_promo_code_id'), 'raw_discounts', ['promo_code_id'], unique=False)
    op.create_index(op.f('ix_raw_discounts_promo_id'), 'raw_discounts', ['promo_id'], unique=False)
    op.create_index(op.f('ix_raw_discounts_store_id'), 'raw_discounts', ['store_id'], unique=False)
    op.create_table('raw_order_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.BigInteger(), nullable=False),
    sa.Column('order_item_id', sa.BigInteger(), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=True),
    sa.Column('stock_id', sa.BigInteger(), nullable=True),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('discount_perc', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=True),
    sa.Column('code', sa.String(length=100), nullable=True),
    sa.Column('tax', sa.String(length=50), nullable=True),
    sa.Column('tax_value', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('loaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raw_order_items_loaded_at'), 'raw_order_items', ['loaded_at'], unique=False)
    op.create_index(op.f('ix_raw_order_items_order_id'), 'raw_order_items', ['order_id'], unique=False)
    op.create_index(op.f('ix_raw_order_items_order_item_id'), 'raw_order_items', ['order_item_id'], unique=False)
    op.create_index(op.f('ix_raw_order_items_product_id'), 'raw_order_items', ['product_id'], unique=False)
    op.create_index(op.f('ix_raw_order_items_store_id'), 'raw_order_items', ['store_id'], unique=False)
    op.create_table('raw_orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('date', sa.String(length=50), nullable=False),
    sa.Column('status_date', sa.String(length=50), nullable=True),
    sa.Column('confirm_date', sa.String(length=50), nullable=True),
    sa.Column('delivery_date', sa.String(length=50), nullable=True),
    sa.Column('status_id', sa.Integer(), nullable=True),
    sa.Column('sum', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=True),
    sa.Column('shipping_id', sa.Integer(), nullable=True),
    sa.Column('shipping_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('code', sa.String(length=100), nullable=True),
    sa.Column('confirm', sa.Boolean(), nullable=True),
    sa.Column('currency_id', sa.Integer(), nullable=True),
    sa.Column('currency_rate', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('paid', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('discount_client', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('discount_group', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('discount_levels', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('discount_code', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('promo_code', sa.String(length=255), nullable=True),
    sa.Column('is_paid', sa.Boolean(), nullable=True),
    sa.Column('total_products', sa.Integer(), nullable=True),
    sa.Column('origin', sa.Integer(), nullable=True),
    sa.Column('status', sa.JSON(), nullable=True),
    sa.Column('billing_address', sa.JSON(), nullable=True),
    sa.Column('delivery_address', sa.JSON(), nullable=True),
    sa.Column('loaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id', 'order_id', name='uq_raw_orders_store_order')
    )
    op.create_index(op.f('ix_raw_orders_email'), 'raw_orders', ['email'], unique=False)
    op.create_index(op.f('ix_raw_orders_loaded_at'), 'raw_orders', ['loaded_at'], unique=False)
    op.create_index(op.f('ix_raw_orders_order_id'), 'raw_orders', ['order_id'], unique=False)
    op.create_index(op.f('ix_raw_orders_status_id'), 'raw_orders', ['status_id'], unique=False)
    op.create_index(op.f('ix_raw_orders_store_id'), 'raw_orders', ['store_id'], unique=False)
    op.create_index(op.f('ix_raw_orders_user_id'), 'raw_orders', ['user_id'], unique=False)
    op.create_table('raw_parcels',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('parcel_id', sa.BigInteger(), nullable=False),
    sa.Column('order_id', sa.BigInteger(), nullable=False),
    sa.Column('shipping_id', sa.Integer(), nullable=True),
    sa.Column('shipping_code', sa.String(length=255), nullable=True),
    sa.Column('weight', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('send_date', sa.String(length=50), nullable=True),
    sa.Column('delivery_date', sa.String(length=50), nullable=True),
    sa.Column('order_date', sa.String(length=50), nullable=True),
    sa.Column('insurance', sa.Boolean(), nullable=True),
    sa.Column('insurance_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('cod', sa.Boolean(), nullable=True),
    sa.Column('cod_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('sent', sa.Boolean(), nullable=True),
    sa.Column('warehouse_id', sa.Integer(), nullable=True),
    sa.Column('delivery_address', sa.JSON(), nullable=True),
    sa.Column('products', sa.JSON(), nullable=True),
    sa.Column('loaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id', 'parcel_id', name='uq_raw_parcels_store_parcel')
    )
    op.create_index(op.f('ix_raw_parcels_loaded_at'), 'raw_parcels', ['loaded_at'], unique=False)
    op.create_index(op.f('ix_raw_parcels_order_id'), 'raw_parcels', ['order_id'], unique=False)
    op.create_index(op.f('ix_raw_parcels_parcel_id'), 'raw_parcels', ['parcel_id'], unique=False)
    op.create_index(op.f('ix_raw_parcels_store_id'), 'raw_parcels', ['store_id'], unique=False)
    op.create_table('raw_payments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('translations', sa.JSON(), nullable=True),
    sa.Column('loaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id', 'payment_id', name='uq_raw_payments_store_payment')
    )
    op.create_index(op.f('ix_raw_payments_loaded_at'), 'raw_payments', ['loaded_at'], unique=False)
    op.create_index(op.f('ix_raw_payments_payment_id'), 'raw_payments', ['payment_id'], unique=False)
    op.create_index(op.f('ix_raw_payments_store_id'), 'raw_payments', ['store_id'], unique=False)
    op.create_table('raw_producers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('producer_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('web', sa.String(length=500), nullable=True),
    sa.Column('isdefault', sa.Boolean(), nullable=True),
    sa.Column('translations', sa.JSON(), nullable=True),
    sa.Column('loaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id', 'producer_id', name='uq_raw_producers_store_producer')
    )
    op.create_index(op.f('ix_raw_producers_loaded_at'), 'raw_producers', ['loaded_at'], unique=False)
    op.create_index(op.f('ix_raw_producers_producer_id'), 'raw_producers', ['producer_id'], unique=False)
    op.create_index(op.f('ix_raw_producers_store_id'), 'raw_producers', ['store_id'], unique=False)
    op.create_table('raw_product_groups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('translations', sa.JSON(), nullable=True),
    sa.Column('loaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id', 'group_id', name='uq_raw_product_groups_store_group')
    )
    op.create_index(op.f('ix_raw_product_groups_group_id'), 'raw_product_groups', ['group_id'], unique=False)
    op.create_index(op.f('ix_raw_product_groups_loaded_at'), 'raw_product_groups', ['loaded_at'], unique=False)
    op.create_index(op.f('ix_raw_product_groups_store_id'), 'raw_product_groups', ['store_id'], unique=False)
    op.create_table('raw_product_stocks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.BigInteger(), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('extended', sa.Boolean(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('default', sa.Boolean(), nullable=True),
    sa.Column('code', sa.String(length=100), nullable=True),
    sa.Column('ean', sa.String(length=50), nullable=True),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('price_wholesale', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('price_special', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('price_buying', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('stock', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('warn_level', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('sold', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('weight', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('availability_id', sa.Integer(), nullable=True),
    sa.Column('delivery_id', sa.Integer(), nullable=True),
    sa.Column('warehouses', sa.JSON(), nullable=True),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.Column('special_offer', sa.JSON(), nullable=True),
    sa.Column('loaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id', 'stock_id', name='uq_raw_product_stocks_store_stock')
    )
    op.create_index(op.f('ix_raw_product_stocks_loaded_at'), 'raw_product_stocks', ['loaded_at'], unique=False)
    op.create_index(op.f('ix_raw_product_stocks_product_id'), 'raw_product_stocks', ['product_id'], unique=False)
    op.create_index(op.f('ix_raw_product_stocks_stock_id'), 'raw_product_stocks', ['stock_id'], unique=False)
    op.create_index(op.f('ix_raw_product_stocks_store_id'), 'raw_product_stocks', ['store_id'], unique=False)
    op.create_table('raw_products',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('type', sa.Integer(), nullable=True),
    sa.Column('producer_id', sa.BigInteger(), nullable=True),
    sa.Column('group_id', sa.BigInteger(), nullable=True),
    sa.Column('category_id', sa.BigInteger(), nullable=True),
    sa.Column('category_tree_id', sa.BigInteger(), nullable=True),
    sa.Column('tax_id', sa.Integer(), nullable=True),
    sa.Column('add_date', sa.String(length=50), nullable=True),
    sa.Column('edit_date', sa.String(length=50), nullable=True),
    sa.Column('code', sa.String(length=100), nullable=True),
    sa.Column('ean', sa.String(length=50), nullable=True),
    sa.Column('currency_id', sa.Integer(), nullable=True),
    sa.Column('stock', sa.JSON(), nullable=True),
    sa.Column('translations', sa.JSON(), nullable=True),
    sa.Column('categories', sa.JSON(), nullable=True),
    sa.Column('loaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id', 'product_id', name='uq_raw_products_store_product')
    )
    op.create_index(op.f('ix_raw_products_category_id'), 'raw_products', ['category_id'], unique=False)
    op.create_index(op.f('ix_raw_products_code'), 'raw_products', ['code'], unique=False)
    op.create_index(op.f('ix_raw_products_group_id'), 'raw_products', ['group_id'], unique=False)
    op.create_index(op.f('ix_raw_products_loaded_at'), 'raw_products', ['loaded_at'], unique=False)
    op.create_index(op.f('ix_raw_products_producer_id'), 'raw_products', ['producer_id'], unique=False)
    op.create_index(op.f('ix_raw_products_product_id'), 'raw_products', ['product_id'], unique=False)
    op.create_index(op.f('ix_raw_products_store_id'), 'raw_products', ['store_id'], unique=False)
    op.create_table('raw_shipments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('shipping_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tax_id', sa.Integer(), nullable=True),
    sa.Column('free_shipping', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('engine', sa.String(length=100), nullable=True),
    sa.Column('translations', sa.JSON(), nullable=True),
    sa.Column('loaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id', 'shipping_id', name='uq_raw_shipments_store_shipping')
    )
    op.create_index(op.f('ix_raw_shipments_loaded_at'), 'raw_shipments', ['loaded_at'], unique=False)
    op.create_index(op.f('ix_raw_shipments_shipping_id'), 'raw_shipments', ['shipping_id'], unique=False)
    op.create_index(op.f('ix_raw_shipments_store_id'), 'raw_shipments', ['store_id'], unique=False)
    op.create_table('raw_statuses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('type', sa.Integer(), nullable=True),
    sa.Column('translations', sa.JSON(), nullable=True),
    sa.Column('loaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id', 'status_id', name='uq_raw_statuses_store_status')
    )
    op.create_index(op.f('ix_raw_statuses_loaded_at'), 'raw_statuses', ['loaded_at'], unique=False)
    op.create_index(op.f('ix_raw_statuses_status_id'), 'raw_statuses', ['status_id'], unique=False)
    op.create_index(op.f('ix_raw_statuses_store_id'), 'raw_statuses', ['store_id'], unique=False)
    op.create_table('raw_subscribers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('subscriber_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('dateadd', sa.String(length=50), nullable=True),
    sa.Column('ipaddress', sa.String(length=50), nullable=True),
    sa.Column('lang_id', sa.Integer(), nullable=True),
    sa.Column('loaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id', 'subscriber_id', name='uq_raw_subscribers_store_sub')
    )
    op.create_index(op.f('ix_raw_subscribers_loaded_at'), 'raw_subscribers', ['loaded_at'], unique=False)
    op.create_index(op.f('ix_raw_subscribers_store_id'), 'raw_subscribers', ['store_id'], unique=False)
    op.create_index(op.f('ix_raw_subscribers_subscriber_id'), 'raw_subscribers', ['subscriber_id'], unique=False)
    op.create_table('raw_taxes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('tax_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('tax_class', sa.String(length=100), nullable=True),
    sa.Column('loaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id', 'tax_id', name='uq_raw_taxes_store_tax')
    )
    op.create_index(op.f('ix_raw_taxes_loaded_at'), 'raw_taxes', ['loaded_at'], unique=False)
    op.create_index(op.f('ix_raw_taxes_store_id'), 'raw_taxes', ['store_id'], unique=False)
    op.create_index(op.f('ix_raw_taxes_tax_id'), 'raw_taxes', ['tax_id'], unique=False)
    op.create_table('raw_user_groups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('discount', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('price_level', sa.Integer(), nullable=True),
    sa.Column('auto_add', sa.Boolean(), nullable=True),
    sa.Column('loaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id', 'group_id', name='uq_raw_user_groups_store_group')
    )
    op.create_index(op.f('ix_raw_user_groups_group_id'), 'raw_user_groups', ['group_id'], unique=False)
    op.create_index(op.f('ix_raw_user_groups_loaded_at'), 'raw_user_groups', ['loaded_at'], unique=False)
    op.create_index(op.f('ix_raw_user_groups_store_id'), 'raw_user_groups', ['store_id'], unique=False)
    op.create_table('shoper_app_installations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('shoper_shop_id', sa.String(length=128), nullable=False),
    sa.Column('shop_url', sa.String(length=255), nullable=False),
    sa.Column('application_code', sa.String(length=128), nullable=True),
    sa.Column('application_version', sa.Integer(), nullable=True),
    sa.Column('trial', sa.Boolean(), nullable=False),
    sa.Column('access_token_encrypted', sa.Text(), nullable=True),
    sa.Column('refresh_token_encrypted', sa.Text(), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('token_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scopes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('installed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('uninstalled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_auth_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shoper_app_installations_shoper_shop_id'), 'shoper_app_installations', ['shoper_shop_id'], unique=True)
    op.create_index(op.f('ix_shoper_app_installations_status'), 'shoper_app_installations', ['status'], unique=False)
    op.create_index(op.f('ix_shoper_app_installations_store_id'), 'shoper_app_installations', ['store_id'], unique=True)
    op.create_table('traffic_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('stat_date', sa.Date(), nullable=False),
    sa.Column('visits', sa.Integer(), nullable=False),
    sa.Column('unique_visitors', sa.Integer(), nullable=False),
    sa.Column('page_views', sa.Integer(), nullable=False),
    sa.Column('orders_count', sa.Integer(), nullable=False),
    sa.Column('revenue', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_traffic_stats_stat_date'), 'traffic_stats', ['stat_date'], unique=False)
    op.create_index(op.f('ix_traffic_stats_store_id'), 'traffic_stats', ['store_id'], unique=False)
    op.create_table('fact_order_items',
    sa.Column('order_item_id', sa.BigInteger(), nullable=False),
    sa.Column('order_id', sa.BigInteger(), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=True),
    sa.Column('category_id', sa.BigInteger(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price_gross', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('unit_price_net', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('discount_value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_gross', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_net', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('order_date', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['fact_orders.order_id'], ),
    sa.PrimaryKeyConstraint('order_item_id')
    )
    op.create_index(op.f('ix_fact_order_items_category_id'), 'fact_order_items', ['category_id'], unique=False)
    op.create_index(op.f('ix_fact_order_items_order_date'), 'fact_order_items', ['order_date'], unique=False)
    op.create_index(op.f('ix_fact_order_items_order_id'), 'fact_order_items', ['order_id'], unique=False)
    op.create_index(op.f('ix_fact_order_items_product_id'), 'fact_order_items', ['product_id'], unique=False)
    op.create_index(op.f('ix_fact_order_items_total_gross'), 'fact_order_items', ['total_gross'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('shoper_order_id', sa.Integer(), nullable=False),
    sa.Column('order_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status_id', sa.Integer(), nullable=True),
    sa.Column('status_name', sa.String(length=100), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('shoper_customer_id', sa.Integer(), nullable=True),
    sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('payment_method', sa.String(length=100), nullable=True),
    sa.Column('shipping_method', sa.String(length=100), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id', 'shoper_order_id', name='uq_orders_store_shoper')
    )
    op.create_index(op.f('ix_orders_order_date'), 'orders', ['order_date'], unique=False)
    op.create_index(op.f('ix_orders_shoper_order_id'), 'orders', ['shoper_order_id'], unique=False)
    op.create_index(op.f('ix_orders_store_id'), 'orders', ['store_id'], unique=False)
    op.create_table('price_update_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.String(length=32), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('row_number', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=200), nullable=False),
    sa.Column('old_price', sa.Float(), nullable=True),
    sa.Column('new_price', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('request_id', sa.String(length=100), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('product_id', sa.BigInteger(), nullable=True),
    sa.Column('stock_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['price_update_jobs.job_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_price_update_logs_job_id'), 'price_update_logs', ['job_id'], unique=False)
    op.create_index(op.f('ix_price_update_logs_seq'), 'price_update_logs', ['seq'], unique=False)
    op.create_table('product_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('stock_quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_snapshots_product_id'), 'product_snapshots', ['product_id'], unique=False)
    op.create_index(op.f('ix_product_snapshots_snapshot_date'), 'product_snapshots', ['snapshot_date'], unique=False)
    op.create_table('order_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('shoper_product_id', sa.Integer(), nullable=True),
    sa.Column('product_code', sa.String(length=100), nullable=True),
    sa.Column('product_name', sa.String(length=500), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tax_value', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_items_order_id'), 'order_items', ['order_id'], unique=False)


def downgrade() -> None:
    op.drop_index(op.f('ix_order_items_order_id'), table_name='order_items')
    op.drop_table('order_items')
    op.drop_index(op.f('ix_product_snapshots_snapshot_date'), table_name='product_snapshots')
    op.drop_index(op.f('ix_product_snapshots_product_id'), table_name='product_snapshots')
    op.drop_table('product_snapshots')
    op.drop_index(op.f('ix_price_update_logs_seq'), table_name='price_update_logs')
    op.drop_index(op.f('ix_price_update_logs_job_id'), table_name='price_update_logs')
    op.drop_table('price_update_logs')
    op.drop_index(op.f('ix_orders_store_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_shoper_order_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_order_date'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_fact_order_items_total_gross'), table_name='fact_order_items')
    op.drop_index(op.f('ix_fact_order_items_product_id'), table_name='fact_order_items')
    op.drop_index(op.f('ix_fact_order_items_order_id'), table_name='fact_order_items')
    op.drop_index(op.f('ix_fact_order_items_order_date'), table_name='fact_order_items')
    op.drop_index(op.f('ix_fact_order_items_category_id'), table_name='fact_order_items')
    op.drop_table('fact_order_items')
    op.drop_index(op.f('ix_traffic_stats_store_id'), table_name='traffic_stats')
    op.drop_index(op.f('ix_traffic_stats_stat_date'), table_name='traffic_stats')
    op.drop_table('traffic_stats')
    op.drop_index(op.f('ix_shoper_app_installations_store_id'), table_name='shoper_app_installations')
    op.drop_index(op.f('ix_shoper_app_installations_status'), table_name='shoper_app_installations')
    op.drop_index(op.f('ix_shoper_app_installations_shoper_shop_id'), table_name='shoper_app_installations')
    op.drop_table('shoper_app_installations')
    op.drop_index(op.f('ix_raw_user_groups_store_id'), table_name='raw_user_groups')
    op.drop_index(op.f('ix_raw_user_groups_loaded_at'), table_name='raw_user_groups')
    op.drop_index(op.f('ix_raw_user_groups_group_id'), table_name='raw_user_groups')
    op.drop_table('raw_user_groups')
    op.drop_index(op.f('ix_raw_taxes_tax_id'), table_name='raw_taxes')
    op.drop_index(op.f('ix_raw_taxes_store_id'), table_name='raw_taxes')
    op.drop_index(op.f('ix_raw_taxes_loaded_at'), table_name='raw_taxes')
    op.drop_table('raw_taxes')
    op.drop_index(op.f('ix_raw_subscribers_subscriber_id'), table_name='raw_subscribers')
    op.drop_index(op.f('ix_raw_subscribers_store_id'), table_name='raw_subscribers')
    op.drop_index(op.f('ix_raw_subscribers_loaded_at'), table_name='raw_subscribers')
    op.drop_table('raw_subscribers')
    op.drop_index(op.f('ix_raw_statuses_store_id'), table_name='raw_statuses')
    op.drop_index(op.f('ix_raw_statuses_status_id'), table_name='raw_statuses')
    op.drop_index(op.f('ix_raw_statuses_loaded_at'), table_name='raw_statuses')
    op.drop_table('raw_statuses')
    op.drop_index(op.f('ix_raw_shipments_store_id'), table_name='raw_shipments')
    op.drop_index(op.f('ix_raw_shipments_shipping_id'), table_name='raw_shipments')
    op.drop_index(op.f('ix_raw_shipments_loaded_at'), table_name='raw_shipments')
    op.drop_table('raw_shipments')
    op.drop_index(op.f('ix_raw_products_store_id'), table_name='raw_products')
    op.drop_index(op.f('ix_raw_products_product_id'), table_name='raw_products')
    op.drop_index(op.f('ix_raw_products_producer_id'), table_name='raw_products')
    op.drop_index(op.f('ix_raw_products_loaded_at'), table_name='raw_products')
    op.drop_index(op.f('ix_raw_products_group_id'), table_name='raw_products')
    op.drop_index(op.f('ix_raw_products_code'), table_name='raw_products')
    op.drop_index(op.f('ix_raw_products_category_id'), table_name='raw_products')
    op.drop_table('raw_products')
    op.drop_index(op.f('ix_raw_product_stocks_store_id'), table_name='raw_product_stocks')
    op.drop_index(op.f('ix_raw_product_stocks_stock_id'), table_name='raw_product_stocks')
    op.drop_index(op.f('ix_raw_product_stocks_product_id'), table_name='raw_product_stocks')
    op.drop_index(op.f('ix_raw_product_stocks_loaded_at'), table_name='raw_product_stocks')
    op.drop_table('raw_product_stocks')
    op.drop_index(op.f('ix_raw_product_groups_store_id'), table_name='raw_product_groups')
    op.drop_index(op.f('ix_raw_product_groups_loaded_at'), table_name='raw_product_groups')
    op.drop_index(op.f('ix_raw_product_groups_group_id'), table_name='raw_product_groups')
    op.drop_table('raw_product_groups')
    op.drop_index(op.f('ix_raw_producers_store_id'), table_name='raw_producers')
    op.drop_index(op.f('ix_raw_producers_producer_id'), table_name='raw_producers')
    op.drop_index(op.f('ix_raw_producers_loaded_at'), table_name='raw_producers')
    op.drop_table('raw_producers')
    op.drop_index(op.f('ix_raw_payments_store_id'), table_name='raw_payments')
    op.drop_index(op.f('ix_raw_payments_payment_id'), table_name='raw_payments')
    op.drop_index(op.f('ix_raw_payments_loaded_at'), table_name='raw_payments')
    op.drop_table('raw_payments')
    op.drop_index(op.f('ix_raw_parcels_store_id'), table_name='raw_parcels')
    op.drop_index(op.f('ix_raw_parcels_parcel_id'), table_name='raw_parcels')
    op.drop_index(op.f('ix_raw_parcels_order_id'), table_name='raw_parcels')
    op.drop_index(op.f('ix_raw_parcels_loaded_at'), table_name='raw_parcels')
    op.drop_table('raw_parcels')
    op.drop_index(op.f('ix_raw_orders_user_id'), table_name='raw_orders')
    op.drop_index(op.f('ix_raw_orders_store_id'), table_name='raw_orders')
    op.drop_index(op.f('ix_raw_orders_status_id'), table_name='raw_orders')
    op.drop_index(op.f('ix_raw_orders_order_id'), table_name='raw_orders')
    op.drop_index(op.f('ix_raw_orders_loaded_at'), table_name='raw_orders')
    op.drop_index(op.f('ix_raw_orders_email'), table_name='raw_orders')
    op.drop_table('raw_orders')
    op.drop_index(op.f('ix_raw_order_items_store_id'), table_name='raw_order_items')
    op.drop_index(op.f('ix_raw_order_items_product_id'), table_name='raw_order_items')
    op.drop_index(op.f('ix_raw_order_items_order_item_id'), table_name='raw_order_items')
    op.drop_index(op.f('ix_raw_order_items_order_id'), table_name='raw_order_items')
    op.drop_index(op.f('ix_raw_order_items_loaded_at'), table_name='raw_order_items')
    op.drop_table('raw_order_items')
    op.drop_index(op.f('ix_raw_discounts_store_id'), table_name='raw_discounts')
    op.drop_index(op.f('ix_raw_discounts_promo_id'), table_name='raw_discounts')
    op.drop_index(op.f('ix_raw_discounts_promo_code_id'), table_name='raw_discounts')
    op.drop_index(op.f('ix_raw_discounts_product_id'), table_name='raw_discounts')
    op.drop_index(op.f('ix_raw_discounts_loaded_at'), table_name='raw_discounts')
    op.drop_index(op.f('ix_raw_discounts_discount_type'), table_name='raw_discounts')
    op.drop_index(op.f('ix_raw_discounts_code'), table_name='raw_discounts')
    op.drop_table('raw_discounts')
    op.drop_index(op.f('ix_raw_customers_user_id'), table_name='raw_customers')
    op.drop_index(op.f('ix_raw_customers_store_id'), table_name='raw_customers')
    op.drop_index(op.f('ix_raw_customers_loaded_at'), table_name='raw_customers')
    op.drop_index(op.f('ix_raw_customers_email'), table_name='raw_customers')
    op.drop_table('raw_customers')
    op.drop_index(op.f('ix_raw_currencies_store_id'), table_name='raw_currencies')
    op.drop_index(op.f('ix_raw_currencies_loaded_at'), table_name='raw_currencies')
    op.drop_index(op.f('ix_raw_currencies_currency_id'), table_name='raw_currencies')
    op.drop_table('raw_currencies')
    op.drop_index(op.f('ix_raw_categories_store_id'), table_name='raw_categories')
    op.drop_index(op.f('ix_raw_categories_loaded_at'), table_name='raw_categories')
    op.drop_index(op.f('ix_raw_categories_category_id'), table_name='raw_categories')
    op.drop_table('raw_categories')
    op.drop_index(op.f('ix_products_store_id'), table_name='products')
    op.drop_index(op.f('ix_products_shoper_product_id'), table_name='products')
    op.drop_index(op.f('ix_products_code'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_price_update_jobs_store_id'), table_name='price_update_jobs')
    op.drop_index(op.f('ix_price_update_jobs_status'), table_name='price_update_jobs')
    op.drop_table('price_update_jobs')
    op.drop_index(op.f('ix_fact_orders_store_id'), table_name='fact_orders')
    op.drop_index(op.f('ix_fact_orders_source_channel'), table_name='fact_orders')
    op.drop_index(op.f('ix_fact_orders_order_status'), table_name='fact_orders')
    op.drop_index(op.f('ix_fact_orders_order_date'), table_name='fact_orders')
    op.drop_index(op.f('ix_fact_orders_gross_value'), table_name='fact_orders')
    op.drop_index(op.f('ix_fact_orders_customer_id'), table_name='fact_orders')
    op.drop_table('fact_orders')
    op.drop_index(op.f('ix_dim_products_store_id'), table_name='dim_products')
    op.drop_index(op.f('ix_dim_products_retail_price'), table_name='dim_products')
    op.drop_index(op.f('ix_dim_products_product_name'), table_name='dim_products')
    op.drop_index(op.f('ix_dim_products_is_active'), table_name='dim_products')
    op.drop_index(op.f('ix_dim_products_category_id'), table_name='dim_products')
    op.drop_index(op.f('ix_dim_products_brand'), table_name='dim_products')
    op.drop_table('dim_products')
    op.drop_index(op.f('ix_dim_customers_total_revenue'), table_name='dim_customers')
    op.drop_index(op.f('ix_dim_customers_store_id'), table_name='dim_customers')
    op.drop_index(op.f('ix_dim_customers_rfm_score'), table_name='dim_customers')
    op.drop_index(op.f('ix_dim_customers_last_order_date'), table_name='dim_customers')
    op.drop_index(op.f('ix_dim_customers_first_order_date'), table_name='dim_customers')
    op.drop_index(op.f('ix_dim_customers_customer_type'), table_name='dim_customers')
    op.drop_table('dim_customers')
    op.drop_index(op.f('ix_customers_store_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_shoper_customer_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_email'), table_name='customers')
    op.drop_table('customers')
    op.drop_table('stores')
    op.drop_index(op.f('ix_raw_ga4_traffic_date'), table_name='raw_ga4_traffic')
    op.drop_table('raw_ga4_traffic')
    op.drop_index(op.f('ix_raw_ga4_sources_date'), table_name='raw_ga4_sources')
    op.drop_table('raw_ga4_sources')
    op.drop_index(op.f('ix_raw_ga4_pages_date'), table_name='raw_ga4_pages')
    op.drop_table('raw_ga4_pages')
    op.drop_index(op.f('ix_raw_ga4_geo_date'), table_name='raw_ga4_geo')
    op.drop_table('raw_ga4_geo')
    op.drop_index(op.f('ix_raw_ga4_funnel_devices_date'), table_name='raw_ga4_funnel_devices')
    op.drop_table('raw_ga4_funnel_devices')
    op.drop_index(op.f('ix_raw_ga4_funnel_date'), table_name='raw_ga4_funnel')
    op.drop_table('raw_ga4_funnel')
    op.drop_index(op.f('ix_raw_ga4_devices_date'), table_name='raw_ga4_devices')
    op.drop_table('raw_ga4_devices')
    op.drop_index(op.f('ix_raw_ga4_cart_products_date'), table_name='raw_ga4_cart_products')
    op.drop_table('raw_ga4_cart_products')
    op.drop_index(op.f('ix_dim_date_year'), table_name='dim_date')
    op.drop_index(op.f('ix_dim_date_week'), table_name='dim_date')
    op.drop_index(op.f('ix_dim_date_quarter'), table_name='dim_date')
    op.drop_index(op.f('ix_dim_date_month'), table_name='dim_date')
    op.drop_index(op.f('ix_dim_date_is_weekend'), table_name='dim_date')
    op.drop_table('dim_date')
    op.drop_index(op.f('ix_dim_categories_parent_id'), table_name='dim_categories')
    op.drop_index(op.f('ix_dim_categories_category_name'), table_name='dim_categories')
    op.drop_table('dim_categories')
    op.drop_table('app_settings')
